config/routes.rb
Tasks::Application.routes.draw do

  root to: 'static_pages#home'
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  match '/contact', to: 'static_pages#contact'  
  
  resources :tasks
  

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :details, :name, :priority, :status
  validates :details, :name, :priority, :status, :presence => true
  
  PRIORITY_TYPES = [
    [ "High" ],
    [ "Medium" ],
    [ "Low" ]
    ]
    
  STATUS_TYPES = [
    ["Pending"],
    ["Complete"]
    ]
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def contact
  end
  
  def help
  end
  
  def about
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def index
     @tasks = Task.all
     @pending_tasks = Task.where("status = ?","Pending")
     @completed_tasks =Task.where("status = ?","Complete")
   end
   
   def show
     @task = Task.find(params[:id])
   end
   
   def edit
     @task = Task.find(params[:id])
   end
   
   def update
     @task = Task.find(params[:id])
     if @task.update_attributes(params[:task])
       redirect_to @task, notice: "Task #{@task.name} updated!"
     else
       render :edit
     end
   end
   
   def new
     @task = Task.new
   end
   
   def create
     @task = Task.new(params[:task])
     if @task.save
       redirect_to @task, notice: "Task #{@task.name} created!"
     else
       render :new
     end
   end
   
   def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_url, notice: "Task was deleted"
   end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Your TO-DO List</a>
    by Farooq Yousuf
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
  		<div class="container">
				<ul class="nav pull-left">
					<li><%= link_to "Your To-do List", root_path, id: "logo" %></li>
					<li><%= link_to "Tasks", tasks_path %></li>
					<li><%= link_to "Add New Task", new_task_path %></li>
				</ul>
				<ul class="nav pull-right">
					<li><%= link_to "Home",  root_path %></li>
					<li><%= link_to "Help",  help_path %></li>
					<li><%= link_to "Sign In",  '#' %></li>
				</ul>
		</div>
	</div>
</header>

app/views/layouts/_shin.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shin' %>
</head>
<body>
	<%= render 'layouts/header'%>
	<div class="container">
		<%= yield %>
	</div>
	<div class="container">
		<%= render 'layouts/footer' %>
	</div>
</div>
</body>
</html>

app/views/static_pages/about.html.erb
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Farooq Yousuf about the TO-DO List App at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
      To get help on this sample app, see the
      <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to Your TO-DO List</h1>

  <h2>
    Making it easy to get stuff done!
  </h2><br>

  <blockquote>
	<p>One of the secrets of getting more done is to make a TO DO List every day,<br> 
		keep it visible, and use it as a guide to action as you go through the day.</p>
	<small>Jean de La Fontaine</small>
  </blockquote><br>

  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/tasks/_form.html.erb
<form class="well">
	<%= form_for(@task) do |f| %>
		<label><%= f.label :name %></label>
		<%= f.text_field :name %>
	
	    <label><%= f.label :details %></label>
		<%= f.text_area :details, cols: 40, rows: 7 %>
	
	    <label><%= f.label :priority %></label>
	    <%= f.select :priority, Task::PRIORITY_TYPES, prompt: "Pick one" %>
	
	    <label><%= f.label :status %></label>
	    <%= f.select :status, Task::STATUS_TYPES, prompt: "Pick one" %><br>
		
		<%= f.submit 'Create Task', :class => 'btn btn-success' %>
		<%= link_to "Cancel", @task, :class => 'btn btn-danger' %>
	<% end %>
</form>

app/views/tasks/_tasks.html.erb
<% tasks_container.each do |task| %>
    
	<header>
      <h2><%= link_to task.name, task %> </h2>
    </header>
			<li><strong>Details</strong>: <%= task.details %></li>
			<li><strong>Priority</strong>: <%= task.priority %></li>
			<li><strong>Status</strong>: <%= task.status %></li><br><br>
<% end %>

app/views/tasks/edit.html.erb
<header>
  <h1>Edit Task: <%= @task.name %></h1>
</header>

<%= render 'form' %>

app/views/tasks/index.html.erb
<%= render "layouts/header" %>

<ul class="nav nav-tabs">
  <li class="active"><a href="#tab1" data-toggle="tab">Pending Tasks</a></li>
  <li><a href="#tab2" data-toggle="tab">All Tasks</a></li>
  <li><a href="#tab3" data-toggle="tab">Completed Tasks</a></li>
</ul>

<div class="tab-content">
	<div class="tab-pane active" id="tab1">
		<%= render :partial => "tasks", :locals => {:tasks_container => @pending_tasks} %>
	</div>
		<div class="tab-pane" id="tab2">
				<%= render :partial => "tasks", :locals => {:tasks_container => @tasks} %>
		</div>
	<div class="tab-pane" id="tab3">
		<%= render :partial => "tasks", :locals => {:tasks_container => @completed_tasks} %>
	</div>
</div>


 

app/views/tasks/new.html.erb
<header>
  <h1>Add New Task</h1>
</header>

<%= render 'form' %>

app/views/tasks/pending.html.erb
<header>
  <h1>Pending Tasks</h1>
</header>
 
<% if @task.staus == "Pending" %>
	<% @tasks.each do |task| %>
    	<header>
      		<h2><%= link_to task.name, task %> </h2>
    	</header>

	    <p><strong>Details</strong>: <%= task.details %></p>
		<p><strong>Priority</strong>: <%= task.priority %></p>
		<p><strong>Status</strong>: <%= task.status %></p>
	
	<% end %>
<% end %>

app/views/tasks/show.html.erb
<table>
  <tr>
    <th colspan="2"><%= @task.name %> </th>
  </tr>
  <tr>
    <td>Details:</td>
    <td><%= @task.details %></td>
  </tr>
  <tr>
    <td>Priority:</td>
    <td><%= @task.priority %></td>
  </tr>
  <tr>
    <td>Status:</td>
    <td><%= @task.status %></td>
  </tr>
</table>
<%= link_to "Edit", edit_task_path(@task) %> |
<%= link_to "Delete", task_path(@task), method: 'delete', 
 										confirm: "Do you really want to delete #{@task.name}?" %>